### ISSUE TITLE
Publish also https://gultsch.de/compliance.html source code

### ISSUE THREAD

**Issue by tuxayo** [iNPUTmice/ComplianceTester#25]
To allow making suggestions and pull requests.

For example:
- tag the XEPs by compliance suites to allow
  - showing only one particular compliance suite XEPs
  - ticking XEPs to show only servers compiling with them

That would be very convenient to search for a server 100% compatible with the Conversations client.

- add static metadata to the servers: (maybe that could go in the report folder, this is an architecture decision)
  - countries which one server legally depends on
  - price
  - IPv6 support
  - warrant canary 

This last part shifts the project beyond XEPs towards a more generic XMPP server comparison.

**Comment by iNPUTmice** [comment]
The source code is already public. Have a look at the files tojson.sh and tohtml.php in the reports folder. Note that these are just some scripts I hacked up in an hour or so to quickly visualize the data.
Currently I have no interest in extending this into a broader XMPP server recommendation page. But feel free to use the data as you like. If you have something I'm willing to link to it.

**Comment by tuxayo** [comment]
Nice, I haven't seen that it was already here.

About the suggestions that are centered on the XEPs (filter by implemented XEPs, show compliance suite)
Could pull requests be accepted? To see if it's useful that I create issues for them and maybe try something if I manage to learn some CSS.

**Comment by iNPUTmice** [comment]
With growing complexity you might no longer go away with the static rendering I'm doing now. Also the code will probably become too complex.
Just take what ever you want from this project and create your own repository. Since I'm not planning on doing more changes there is simply no point in merging your developments into my repository. (Not even considering the fact that there is no point in have the actual compliance tester and the visualization in the same repository.)
Like I said I'm willing to link to your repository or website as soon as you have something ready.

**Comment by tuxayo** [comment]
No problem. If I keep using XMPP on the long run I'll definitely consider trying something like you suggested to make choosing a server easier.

Thanks for your work!
